### ISSUE TITLE
关于《互动直播中的前端技术 -- 即时通讯》里的小问题

### ISSUE THREAD

**Issue by objcxiaobai** [x-orpheus/blog#3]
### 超时处理
```
onMessage(packet) {
        const data = parsePacket(packet);
        if (data.seq) {
            const cmdTask = this.cmdTasksMap[data.seq];
            if (cmdTask) {
               //问题代码：
               //不是this.seq,而是data.seq,因为this.seq已经+1了
                clearTimeout(this.timeMap[this.seq]);
                delete this.timeMap[this.seq];
                if (data.body.code === 200) {
                    cmdTask.resolve(data.body);
                } else {
                    cmdTask.reject(data.body);
                }
                delete this.cmdTasksMap[data.seq];
            }
        }
    }
```
关于**心跳包**

在sendCmd中指定heartbeat类型seq为0，让业务包连续编号

我假设心跳包传参为data.seq=0
在onMessage回调函数中，需要特殊处理才对。
文章这一块代码没有特殊处理，除此之外缺失 delete this.timeMap[data.seq];

**Comment by www-wwj** [comment]
这里笔误了，是要根据ack包的（即data.seq）。
心跳包一般正常回包不处理的，异常才处理，有业务逻辑可以加的，这里只是简单写下处理逻辑。

**Comment by objcxiaobai** [comment]
> 这里笔误了，是要根据ack包的（即data.seq）。
> 心跳包一般正常回包不处理的，异常才处理，有业务逻辑可以加的，这里只是简单写下处理逻辑。

谢谢回复，抱歉，我可能没有提好问题。
正常来说心跳包，也会走onMessage函数的，这里应该有逻辑区分吧？
比如说data.seq == 0 的时候，就简简单单consolo.log一下
data.seq其他情况下该处理的处理。

关于文章中“重连机制” 没有get到

**Comment by www-wwj** [comment]
> 正常来说心跳包，也会走onMessage函数的，这里应该有逻辑区分吧？
> 比如说data.seq == 0 的时候，就简简单单consolo.log一下

是的，可以这样。

> data.seq其他情况下该处理的处理。

对的，比如服务端直接下发的通知（不是主动发的都不会有客户端序列号），要根据具体的data执行不同的回调

> 关于文章中“重连机制” 没有get到

服务器通常会给你一次多个地址去建立长链接，异常情况首先尝试当前的长链接重试下，连不上就干掉这个地址换下一个，要是用完了在服务器去要。但是实在连不上最终还是要上层兜底，具体策略根据业务情况调整。

**Comment by objcxiaobai** [comment]
> > 正常来说心跳包，也会走onMessage函数的，这里应该有逻辑区分吧？
> > 比如说data.seq == 0 的时候，就简简单单consolo.log一下
> 
> 是的，可以这样。
> 
> > data.seq其他情况下该处理的处理。
> 
> 对的，比如服务端直接下发的通知（不是主动发的都不会有客户端序列号），要根据具体的data执行不同的回调
> 
> > 关于文章中“重连机制” 没有get到
> 
> 服务器通常会给你一次多个地址去建立长链接，异常情况首先尝试当前的长链接重试下，连不上就干掉这个地址换下一个，要是用完了在服务器去要。但是实在连不上最终还是要上层兜底，具体策略根据业务情况调整。

明白，假设有个场景成功发送消息但突然断连但重新连上去了，存储在 `cmdTasksMap` 的 promise 回调，是否在onOpen回掉重新执行？还是清除？如果是大哥你会怎么操作？

**Comment by www-wwj** [comment]
回调给上层处理。。。

**Comment by www-wwj** [comment]
回调 超时error跟你发送的消息体（带上消息客户端的唯一id）给上层 做个重试。重试的时候服务端可以根据你的id去重的。

**Comment by objcxiaobai** [comment]
> 回调 超时error跟你发送的消息体（带上消息客户端的唯一id）给上层 做个重试。重试的时候服务端可以根据你的id去重的。

大哥您好，**“上层“** 和 **”上层兜底“**，我不太明白这两个词的意思，我的理解是服务器那边的事情。能否解惑？
